repos:
- repo: local
  hooks:
  - id: linter-hook
    name: lint and fix possible errors with ruff
    entry: pdm run ruff check ./src/ --fix
    types: [python]
    language: python
    verbose: true
    language_version: "3.12"
  - id: format-hook
    name: format files with ruff
    entry: pdm run ruff format ./src/
    types: [python]
    language: python
    verbose: true
    language_version: "3.12"
